:Author: Laxmipriyadharshini
:Email: Laxmipriyadharshini@gmail.com
:Date: 02/10/2019
:Revision: v1.2
/*----------- Configuration Management -------------
v1.0 Basic arduino Circuit connection and setup
V1.1 Setting up LED
v1.2 Connection to Moisture sensor
------------------------*/
:License: Public Domain

= Project: Water my plant

Describe your project

== Step 1: Installation
Please describe the steps to install this project.
The main aim of this hands on project is to build a simple device that tells you when to water a plant. Wiring together and writing code for an Arduino, LEDs, moisture sensor, and Bluetooth module. The moisture sensors are used to measure the current moisture of the pot and are reported. My future plan, maybe over the upcoming weekends, is to extend the project to send notifications to mobile based on the moisture reading on when to water the plant.
For example:

1. Open this file
2. Edit as you like
3. Release to the World

== Step 2: Assemble the circuit

Assemble the circuit following the diagram layout.png attached to the sketch


== Step 3: Load the code

Upload the code contained in this sketch on to your board

=== Folder structure

....
 sketch123                => Arduino sketch folder
  ├── sketch123.ino       => main Arduino file
  ├── schematics.png      => (optional) an image of the required schematics
  ├── layout.png          => (optional) an image of the layout
  └── ReadMe.adoc         => this file
....


=== Contributing
To contribute to this project please contact Laxmipriyadharshini https://id.arduino.cc/Laxmipriyadharshini

=== BOM
Add the bill of the materials you need for this project.

|===
| ID | Part name      | Part number | Quantity
| R1 | 10k Resistor   | 1234-abcd   | 10
| L1 | Red LED        | 2345-asdf   | 5
| A1 | Arduino Zero   | ABX00066    | 1
|===


=== Help
This document is written in the _AsciiDoc_ format, a markup language to describe documents.
If you need help you can search the http://www.methods.co.nz/asciidoc[AsciiDoc homepage]
or consult the http://powerman.name/doc/asciidoc[AsciiDoc cheatsheet]
